In [145]:
import pandas as pd
import json

In [146]:
wc_2010df = pd.read_csv('./source_raw_data/worldcup_2010.csv')
wc_2014df = pd.read_csv('./source_raw_data/worldcup2014.csv', sep=";")
wc_2022df = pd.read_csv('./source_raw_data/worldcup_2022.csv')
wc_2022_dfclara = pd.read_csv('./source_raw_data/fifa-world-cup-2022-UTC.csv')

2018

In [147]:
with open('./source_raw_data/worldcup_2018.json') as file:
    data = json.load(file)
team_map = {team['id']: team['name'] for team in data['teams']}
stadium_map = {stadium['id']: stadium['city'] for stadium in data['stadiums']}
matches_list = []

def process_matches(match_data, edition_name, round_name):
    for match in match_data:
        match_info = {
            'id_match': match['name'],
            'home_team': team_map[match['home_team']],
            'away_team': team_map[match['away_team']],
            'home_result': match['home_result'],
            'away_result': match['away_result'],
            'date': match['date'],
            'round': round_name,
            'city': stadium_map[match['stadium']],
            'édition': edition_name
        }
        matches_list.append(match_info)

for group_key, group_data in data['groups'].items():
    process_matches(group_data['matches'], '2018-RUSSIA', 'Group')

knockout_rounds = {
    'round_16': 'Round of 16',
    'round_8': 'Quarter-finals',
    'round_4': 'Semi-finals',
    'round_2_loser': 'Third place play-off',
    'round_2': 'Final'
}

for round_key, round_name in knockout_rounds.items():
    process_matches(data['knockout'][round_key]['matches'], '2018-RUSSIA', round_name)

df_2018 = pd.DataFrame(matches_list)

print(df_2018.head())

   id_match home_team     away_team  home_result  away_result  \
0         1    Russia  Saudi Arabia            5            0
1         2     Egypt       Uruguay            0            1
2        17    Russia         Egypt            3            1
3        18   Uruguay  Saudi Arabia            1            0
4        33   Uruguay        Russia            3            0

                        date  round              city      édition
0  2018-06-14T18:00:00+03:00  Group            Moscow  2018-RUSSIA
1  2018-06-15T17:00:00+05:00  Group     Yekaterinburg  2018-RUSSIA
2  2018-06-19T21:00:00+03:00  Group  Saint Petersburg  2018-RUSSIA
3  2018-06-20T18:00:00+03:00  Group     Rostov-on-Don  2018-RUSSIA
4  2018-06-25T18:00:00+04:00  Group            Samara  2018-RUSSIA

1930-2010

In [148]:
file_path = './source_raw_data/worldcup_2010.csv'
data = pd.read_csv(file_path)

data['id_match'] = range(1, len(data) + 1)

def extract_results(score):
    try:
        score = score.split(' ')[0]  
        home_score, away_score = map(int, score.split('-'))
        return home_score, away_score
    except (ValueError, IndexError):
        return None, None  

data[['home_result', 'away_result']] = data['score'].apply(lambda x: pd.Series(extract_results(x)))
data['date'] = pd.to_datetime(data['year'].astype(str) + '-01-01')
data['city'] = data['venue'].str.split('.').str[0]
df_19302010 = data[['id_match', 'team1', 'team2', 'home_result', 'away_result', 'date', 'round', 'city', 'edition']]
df_19302010.rename(columns={
    'id_match': 'id_match',
    'team1': 'home_team',          
    'team2': 'away_team',          
    'edition': 'édition'}, inplace=True)
df_19302010 = df_19302010[df_19302010['édition'] != '2014-BRAZIL']
print(df_19302010.head())

   id_match                 home_team         away_team  home_result  \
0         1                    France   Mexico (México)          4.0
1         2                       USA  Belgium (België)          3.0
2         3  Yugoslavia (Југославија)   Brazil (Brasil)          2.0
3         4         Romania (România)       Peru (Perú)          3.0
4         5                 Argentina            France          1.0

   away_result       date        round        city       édition
0          1.0 1930-01-01  GROUP_STAGE  Montevideo  1930-URUGUAY
1          0.0 1930-01-01  GROUP_STAGE  Montevideo  1930-URUGUAY
2          1.0 1930-01-01  GROUP_STAGE  Montevideo  1930-URUGUAY
3          1.0 1930-01-01  GROUP_STAGE  Montevideo  1930-URUGUAY
4          0.0 1930-01-01  GROUP_STAGE  Montevideo  1930-URUGUAY

C:\Users\Chucky Babe\AppData\Local\Temp\ipykernel_41248\3823762620.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_19302010.rename(columns={

2022

In [149]:
file_path = './source_raw_data/worldcup_2022.csv'
df = pd.read_csv(file_path)

df_2022 = pd.DataFrame()

df_2022['id_match'] = range(1, len(df) + 1)

df_2022['home_team'] = df['team1']
df_2022['away_team'] = df['team2']
df_2022['home_result'] = df['number of goals team1']
df_2022['away_result'] = df['number of goals team2']
df_2022['date'] = df['date']
df_2022['round'] = df['category']
df_2022['city'] = 'Inconnue' 
df_2022['édition'] = '2022-QATAR' 
print(df_2022.head())

   id_match      home_team     away_team  home_result  away_result  \
0         1          QATAR       ECUADOR            0            2
1         2        ENGLAND          IRAN            6            2
2         3        SENEGAL   NETHERLANDS            0            2
3         4  UNITED STATES         WALES            1            1
4         5      ARGENTINA  SAUDI ARABIA            1            2

          date    round      city     édition
0  20 NOV 2022  Group A  Inconnue  2022-QATAR
1  21 NOV 2022  Group B  Inconnue  2022-QATAR
2  21 NOV 2022  Group A  Inconnue  2022-QATAR
3  21 NOV 2022  Group B  Inconnue  2022-QATAR
4  22 NOV 2022  Group C  Inconnue  2022-QATAR

2014

In [150]:
df = pd.read_csv('./source_raw_data/worldcup2014.csv', sep=';', encoding='utf-8')

df_2014 = pd.DataFrame({
    'id_match': range(1, len(df) + 1),  
    'home_team': df['Home Team Name'],
    'away_team': df['Away Team Name'],
    'home_result': df['Home Team Goals'],
    'away_result': df['Away Team Goals'],
    'date': df['Datetime'],  
    'round': df['Stage'],  
    'city': df['City'],
    'édition': '2014-BRAZIL' 
})
print(df_2014.head())

   id_match home_team    away_team  home_result  away_result  \
0         1    Brazil      Croatia            3            1
1         2    Mexico     Cameroon            1            0
2         3     Spain  Netherlands            1            5
3         4     Chile    Australia            3            1
4         5  Colombia       Greece            3            0

                   date    round             city      édition
0  12 Jun 2014 - 17:00   Group A       Sao Paulo   2014-BRAZIL
1  13 Jun 2014 - 13:00   Group A           Natal   2014-BRAZIL
2  13 Jun 2014 - 16:00   Group B        Salvador   2014-BRAZIL
3  13 Jun 2014 - 18:00   Group B          Cuiaba   2014-BRAZIL
4  14 Jun 2014 - 13:00   Group C  Belo Horizonte   2014-BRAZIL

Complete

In [151]:
combined_df = pd.concat([df_19302010, df_2014, df_2018, df_2022], ignore_index=True)
combined_df.reset_index(drop=True, inplace=True)
combined_df['id_match'] = range(1, len(combined_df) + 1)
combined_df

,id_match,home_team,away_team,home_result,away_result,date,round,city,édition
0,1,France,Mexico (México),4.0,1.0,1930-01-01 00:00:00,GROUP_STAGE,Montevideo,1930-URUGUAY
1,2,USA,Belgium (België),3.0,0.0,1930-01-01 00:00:00,GROUP_STAGE,Montevideo,1930-URUGUAY
2,3,Yugoslavia (Југославија),Brazil (Brasil),2.0,1.0,1930-01-01 00:00:00,GROUP_STAGE,Montevideo,1930-URUGUAY
3,4,Romania (România),Peru (Perú),3.0,1.0,1930-01-01 00:00:00,GROUP_STAGE,Montevideo,1930-URUGUAY
4,5,Argentina,France,1.0,0.0,1930-01-01 00:00:00,GROUP_STAGE,Montevideo,1930-URUGUAY
...,...,...,...,...,...,...,...,...,...
6618,6619,ENGLAND,FRANCE,1.0,2.0,10 DEC 2022,Quarter-final,Inconnue,2022-QATAR
6619,6620,ARGENTINA,CROATIA,3.0,0.0,13 DEC 2022,Semi-final,Inconnue,2022-QATAR
6620,6621,FRANCE,MOROCCO,2.0,0.0,14 DEC 2022,Semi-final,Inconnue,2022-QATAR
6621,6622,CROATIA,MOROCCO,2.0,1.0,17 DEC 2022,Play-off for third place,Inconnue,2022-QATAR
6622,6623,ARGENTINA,FRANCE,3.0,3.0,18 DEC 2022,Final,Inconnue,2022-QATAR

In [161]:
df_equal = combined_df[combined_df['home_result'] == combined_df['away_result']]
df_equal

,id_match,home_team,away_team,home_result,away_result,date,round,city,édition,winner,goal_difference
20,21,Yugoslavia (Југославија),Switzerland (Schweiz / Suisse),2.0,2.0,1933-01-01 00:00:00,PRELIMINARY-Europe,Beograd,1934-ITALY,None,0.0
24,25,Haiti (Haïti),Cuba,1.0,1.0,1934-01-01 00:00:00,PRELIMINARY-N/C.America,Port-au-Prince,1934-ITALY,None,0.0
26,27,Irish Free State (Saorstát Éireann),Belgium (België),4.0,4.0,1934-01-01 00:00:00,PRELIMINARY-Europe,Dublin,1934-ITALY,None,0.0
55,56,Italy (Italia),Spain (España),1.0,1.0,1934-01-01 00:00:00,1/4_FINAL,Firenze,1934-ITALY,None,0.0
71,72,Irish Free State (Saorstát Éireann),Norway (Norge),3.0,3.0,1937-01-01 00:00:00,PRELIMINARY-Europe,Dublin,1938-FRANCE,None,0.0
...,...,...,...,...,...,...,...,...,...,...,...
6611,6612,JAPAN,CROATIA,1.0,1.0,05 DEC 2022,Round of 16,Inconnue,2022-QATAR,None,0.0
6613,6614,MOROCCO,SPAIN,0.0,0.0,06 DEC 2022,Round of 16,Inconnue,2022-QATAR,None,0.0
6615,6616,CROATIA,BRAZIL,1.0,1.0,09 DEC 2022,Quarter-final,Inconnue,2022-QATAR,None,0.0
6616,6617,NETHERLANDS,ARGENTINA,2.0,2.0,09 DEC 2022,Quarter-final,Inconnue,2022-QATAR,None,0.0
6622,6623,ARGENTINA,FRANCE,3.0,3.0,18 DEC 2022,Final,Inconnue,2022-QATAR,None,0.0

In [153]:
# Déterminer le gagnant
def determine_winner(row):
    if row['home_result'] > row['away_result']:
        return row['home_team']
    elif row['home_result'] < row['away_result']:
        return row['away_team']
    else:
        return None  # Match nul

combined_df['winner'] = combined_df.apply(determine_winner, axis=1)

# Compter les victoires par pays
most_wins = combined_df['winner'].value_counts().idxmax()
most_wins_count = combined_df['winner'].value_counts().max()

print(f"Le pays qui a gagné le plus de matchs en Coupe du Monde est : {most_wins} avec {most_wins_count} victoires.")

Le pays qui a gagné le plus de matchs en Coupe du Monde est : Brazil (Brasil) avec 123 victoires.

In [156]:
combined_df['winner'] = combined_df.apply(determine_winner, axis=1)

# Filtrer pour les finales
finals = combined_df[combined_df['round'] == 'Final']

In [157]:

# Compter les victoires en finale
top_winners = finals['winner'].value_counts()

# Afficher le top des vainqueurs de Coupe du Monde (finales)
print("\nTop des vainqueurs de Coupe du Monde (finales) :")
if top_winners.empty:
    print("Aucun vainqueur n'a été trouvé.")
else:
    for idx, count in top_winners.items():
        print(f"{idx}: {count} victoire(s)")

Top des vainqueurs de Coupe du Monde (finales) :
Germany: 2 victoire(s)
France: 1 victoire(s)

In [159]:
# Calculer l'écart de buts
combined_df['goal_difference'] = (combined_df['home_result'] - combined_df['away_result']).abs()

# Trouver le plus grand écart
max_goal_difference = combined_df['goal_difference'].max()

print(f"\nLe plus grand écart de buts dans un match est : {max_goal_difference}.")

Le plus grand écart de buts dans un match est : 31.0.